WITH

MAINTABLE AS 
(
	SELECT TBLRESPONSIBILITIES.SUPPLIER, SUPPLIER_ALIGNMENT.SUPPLIERNAME, TBLCONTACT.[FIRST], TBLCONTACT.[LAST], TBLCONTACT.MOBILE, 
	TBLCONTACT.EMAIL AS SUPPLIER_EMAIL, SPA_ALIGNMENT.SPA AS SUPPLIER_PERFORMANCE_ANALYST, SPA_ALIGNMENT.EMAIL AS SPA_EMAIL, 
	TBLRESPONSIBILITIES.ROLE

	FROM ITEMMANAGEMENT.DBO.TBLCONTACT
	INNER JOIN ITEMMANAGEMENT.DBO.TBLRESPONSIBILITIES
	ON TBLCONTACT.CONTACTID = TBLRESPONSIBILITIES.CONTACTID
	INNER JOIN ITEMMANAGEMENT.DBO.SUPPLIER_ALIGNMENT 
	ON TBLRESPONSIBILITIES.SUPPLIER = SUPPLIER_ALIGNMENT.SUPPLIERNUMBER
	INNER JOIN ITEMMANAGEMENT.DBO.SPA_ALIGNMENT 
	ON SUPPLIER_ALIGNMENT.SUPPLIERGROUP = SPA_ALIGNMENT.SUPPLIERGROUP

	WHERE TBLRESPONSIBILITIES.SUPPLIER IS NOT NULL
	AND SUPPLIER_ALIGNMENT.SUPPLIERNAME IS NOT NULL
	AND TBLCONTACT.EMAIL IS NOT NULL
	AND SPA_ALIGNMENT.SPA IS NOT NULL
	AND SPA_ALIGNMENT.EMAIL IS NOT NULL
),

HAS_ROLE AS
(
	SELECT SUPPLIER, SUPPLIERNAME, SUPPLIER_EMAIL, [ROLE], SUPPLIER_PERFORMANCE_ANALYST, 
	SPA_EMAIL, 'HAS_ROLE' AS ROLE_FLAG 
	
	FROM MAINTABLE
	WHERE [ROLE] IN ('PRIMARY', 'OPERATIONS')
),

NO_ROLE AS 
(
	SELECT SUPPLIER, SUPPLIERNAME, SUPPLIER_EMAIL, [ROLE], SUPPLIER_PERFORMANCE_ANALYST, 
	SPA_EMAIL, 'NO_ROLE' AS ROLE_FLAG
	
	FROM MAINTABLE
	WHERE SUPPLIER NOT IN (SELECT DISTINCT SUPPLIER FROM HAS_ROLE)
)

SELECT * FROM HAS_ROLE 
UNION
SELECT * FROM NO_ROLE